### PR TITLE
Fixes for readme, opengaze, and eyelink

### PR DESCRIPTION
**Pull request by smathot**
This PR contains:

- stability and performance improvements for OpenGaze
- more liberal parameters for gaze-contingent drift correction with the EyeLink to avoid getting stuck when using very high-resolution monitors
- Improved readme and inclusion of readme in setup for PyPi

### CODE REVIEW

**Comment by esdalmaijer** [comment]
As for the README being used in setup.py, there's a bug with parsing Markdown code that might prevent it from compiling the wheel. I'll check if it persists (might've been solved since I last ran into it), and if it does, I'll remove it again.

**Comment by smathot** [comment]
Can you still release this on PyPi?

**Comment by esdalmaijer** [comment]
Done! Can we bump it to a full version? It's currently listed as pre-release (0.7.5a5), but it looks like there's nothing untested in there?

**Comment by smathot** [comment]
:+1: And yes, I would bump it to 0.7.5. (I always use a prerelease version number during development and then bump it right before the actual release.)

**Pull request merged**
